version: '3'
services:
    todomvc:
        build: .
        image: todomvc
        command: todomvc
        expose:
            - "1234"
    nginx:
        build: ./nginx
        image: nginx
        ports:
            - "8080:80"
        depends_on:
            - todomvc
